### ISSUE TITLE
Update instructions to point folks to template issue

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/gsoc#12]
I created a template for proposing GSoC projects. Maybe it's not a great idea, but I wanted to give it a shot. I was thinking folks could put their project proposals in as tickets to this repo, instead of having them spread around different places.
![image](https://user-images.githubusercontent.com/8480023/152430707-9164cdc0-369d-43f4-948b-a3278c06e37f.png)

**Comment by ocefpaf** [comment]
It is a good idea! We need to post links to past good proposals as examples in there.

**Comment by mwengren** [comment]
Changes to make to: https://github.com/ioos/gsoc/blob/main/.github/ISSUE_TEMPLATE/gsoc-project-proposal.md as part of this:

- [ ] Update Labels front matter/header to use GSoC23
- [ ] Include estimate project duration (175 or 350?)
- [ ] Any other info we need to collect?

**Comment by mwengren** [comment]
Ok, I think my most recent commits fd8ada7b6fc414d47223909cb89940cf1a8ce4f0 and 60cf9551d065a5ce61c863b2687fc3809d010b7e addressed this.  Hopefully we're all set to accept new project ideas from mentors now.  Let's get the word out!
