### ISSUE TITLE
Making ocean biodiversity data easily accessible with python (pyobis revamp)

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/gsoc#15]
Project Description:

The [Ocean Biodiversity Information System (OBIS)](https://obis.org/) is a global open-access data and information clearing-house on marine biodiversity for science, conservation and sustainable development. OBIS harvests occurrence records from thousands of datasets and makes them available as a single integrated dataset via [various services](https://obis.org/manual/access/) including the [OBIS API](https://api.obis.org/). This project is intended to update the existing [pyobis](https://github.com/iobis/pyobis) python package to use the new OBIS API and ensure the package is usable for product generation in the future. 

Expected Outcomes: 

* Update pyobis to use new API. 
* Make mof response more efficient. 
* Create tutorial usage of each module. 
* Clarify listing of GBIF instead of OBIS in package descrip [ref](https://github.com/iobis/pyobis/blob/master/setup.py#L25). 
* Increase test coverage. 
* Use CI push to PyPI. 
* Merge in URL changes done on the forks. 
* Create jupyter notebook with demo to analyze/visualize data grabbed using this package.

Skills required:

* Python
* Some knowledge/use of Web Application Programming Interfaces (API)

Difficulty:

* Moderate

Mentor(s):

Tylar Murray (@7yl4r), Filipe Fernandes (@ocefpaf), Mathew Biddle (@MathewBiddle)

**Comment by Krish2208** [comment]
Hello Sir,
I am Krish Agrawal and would like to contribute to this project, can you please help me with the process and can you please tell me about the contribution guidelines and proposal format.

Thank You

**Comment by ayushanand18** [comment]
Hi @MathewBiddle @7yl4r @ocefpaf, I am Ayush Anand, a Computer Science Undergrad from the National Institute of Technology Durgapur, India. I have been working on Deep Learning and Data Science for 2 years now and my previous projects have focused on various parts of a data science pipeline including CI/CD. I have prior experiences working with REST APIs and even creating one for an old project for a machine learning-powered app.

I would like to work on this particular project as it aligns perfectly well with my research interests as well as my past projects. Here's my Kaggle in case you wish to look at my Data Visualization portfolio: https://kaggle.com/theayushanand.

**Comment by ayushanand18** [comment]
I would also like to ask if I shall proceed with making a PR/fork of the pyobis package or there are any tasks to headstart with? Thanks in advance!

**Comment by ocefpaf** [comment]
> I would also like to ask if I shall proceed with making a PR/fork of the pyobis package or there are any tasks to headstart with? Thanks in advance!

Sure. Sending some PRs is a nice way to demonstrate your interest in the project and start learning about the code base. However, remember that we will select students based on the project proposal. I recommend you to work on a proposal based on the ideas page.

Feel free to share a draft with us in case you need guidance.

**Comment by Krish2208** [comment]
> > I would also like to ask if I shall proceed with making a PR/fork of the pyobis package or there are any tasks to headstart with? Thanks in advance!
> 
> Sure. Sending some PRs is a nice way to demonstrate your interest in the project and start learning about the code base. However, remember that we will select students based on the project proposal. I recommend you to work on a proposal based on the ideas page.
> 
> Feel free to share a draft with us in case you need guidance.

Can you share a basic structure of the proposal, I mean what all things do we need to mention or is the proposal structure open?

**Comment by ocefpaf** [comment]
> Can you share a basic structure of the proposal, I mean what all things do we need to mention or is the proposal structure open?

You can view past projects in https://summerofcode.withgoogle.com/archive/2021/organizations/5159672092295168#projects-list

**Comment by ayushanand18** [comment]
> > Can you share a basic structure of the proposal, I mean what all things do we need to mention or is the proposal structure open?
> 
> You can view past projects in https://summerofcode.withgoogle.com/archive/2021/organizations/5159672092295168#projects-list

Thanks a ton @ocefpaf

**Comment by pushkar2112** [comment]
Hi,
I am Pushkar Verma a First-year Computer Science student from India. I would very much like to contribute to this project. I am experienced in python centric development and have past experience with REST APIs as I have previously used them in my projects. 
I have started to make myself familiar with the codebase and, am optimistic about the project. Also, I have an idea that I would like to discuss.

Looking forward to this amazing opportunity
Cheers!!

**Comment by ayushanand18** [comment]
@ocefpaf Hope you are doing great! I have drafted a proposal for the pyobis revamp project. Please have a look at it and provide your valuable feedback on it: [https://docs.google.com/document/d/1HJeqiE6WnYCDmtLmssUgwSEqy70yTgb5eifLu3FOUP0/edit?usp=sharing](https://docs.google.com/document/d/1HJeqiE6WnYCDmtLmssUgwSEqy70yTgb5eifLu3FOUP0/edit?usp=sharing). Your feedback will help me improve a lot!

Thanks in advance...

**Comment by ayushanand18** [comment]
Also, I tried updating the modules to OBIS API v3, and I am glad to share that I was successful in editing the occurrence module, and only minor changes are required to integrate other modules. Using the actual package from PyPI got me some errors like "could not make connection", so I edited and ran the dev version on my local machine. You can view the Commit 7a6630a, [https://github.com/ayushanand18/pyobis/commit/7a6630a52a1c41cf9f48f1edef5987a08b4e54d1](https://github.com/ayushanand18/pyobis/commit/7a6630a52a1c41cf9f48f1edef5987a08b4e54d1) in gsoc2022-working-aa branch (on my fork). I am waiting for inputs from you to move towards editing the other modules and initiating a PR. Thanks once again.

**Comment by ayushanand18** [comment]
@ocefpaf @7yl4r @MathewBiddle I have changed the pyobis/groups, nodes, occurrences, checklist, taxa modules to integrated them with OBIS v3 API. These changes are minor to make the GET requests in line with the v3 API (as on Swagger [here](https://api.obis.org/#/)).\
But I had some questions.
+ I was not able to find the API reference for existing pyobis/resources and pyobis/groups.
+ Also, I cannot find existing modules for some paths in the API references: dataset, Institute, Area, Country, Facet, Statistics. So shall I proceed towards creating modules for the same?
Here's the PR for your reference, https://github.com/iobis/pyobis/pull/8

Looking forward to your suggestions...

**Comment by ayushanand18** [comment]
@ocefpaf @MathewBiddle @7yl4r Could you please help me out? While trying out the OBIS API v3 on Swagger, I get the `mof` value as *null every time I iter through the /occurrence resource. I am also attaching a screenshot for your reference.

Thank you for your time!

<img width="826" alt="image" src="https://user-images.githubusercontent.com/36472216/159490333-39f92195-8713-4644-81e3-e054aba92fd7.png">

Also, do we have a Slack channel to discuss issues and get solutions?

**Comment by ocefpaf** [comment]
We will have a slack channel when GSoC starts. For now we can use the GH issues on the problem main repository to keep the notifications more focused on the pre-selection PRs. BTW, I'll be a bit slow to respond over the next few weeks.

**Comment by ayushanand18** [comment]
Thanks a ton @ocefpaf, I'll surely write issues of the main repository directly.

**Comment by ayushanand18** [comment]
> @ayushanand18, @Krish2208, and @pushkar2112 sorry for being MIA, had some health issues in the family.
> 
> Please be sure to send your proposal before the 19th. If you want to share a draft with us for a review you can do so.
> 
> Hope to see your proposals soon. Good luck!

@ocefpaf I hope everything is good now. I wrote an email to you seeking your guidance on my proposal. Your feedback on it would help me improve a lot. Thanks in advance! :)

**Comment by pushkar2112** [comment]
@ocefpaf Hi, 
I have sent you an email, seeking feedback and guidance on my project proposal. Your feedback on it would prove very helpful for me.
Thanks!😀

**Comment by ayushanand18** [comment]
@ocefpaf @MathewBiddle @7yl4r Hope you are doing great, I am sure IOOS Code Sprint would have gone really well! 

I would like to sincerely thank you all for your guidance and support throughout the application period and before. It's been an amazing experience so far, and I am really excited for the future working under your guidance and the learnings that lie ahead. This would be incomplete without the mention of @pieterprovoost for helping me out every time I was stuck, and for the great code reviews - thank you so much. Indeed, Open source is a beautiful community that becomes prettier with each contribution. 

Thanks a ton once again! :)

**Comment by ocefpaf** [comment]
Glad you are excited for the next steps. I'm closing this issue for now and we will be in touch shorty. Thanks to all that applied and for all the amazing proposals that you submitted.
