### ISSUE TITLE
Interactive visualization of cloud-hosted ocean sonar data

### ISSUE THREAD

**Issue by leewujung** [ioos/gsoc#16]
**Project Description:**

Ocean sonar systems, such as echosounders, are the [workhorse to study life in the ocean](https://storymaps.arcgis.com/stories/e245977def474bdba60952f30576908f). They provide continuous observations of fish and zooplankton by transmitting sounds and analyzing the echoes bounced off these animals, just like how medical ultrasound images the interior of human body. In recent years these systems are widely deployed on ships, autonomous vehicles, or moorings, bringing in a lot of data that allow scientists to study the change of the marine ecosystem.

This project aims to create the capability to interactively visualize large, cloud-based ocean sonar data to accelerate data exploration and discovery. Developments in this project will go hand-in-hand with ongoing development of the [echopype](https://github.com/OSOceanAcoustics/echopype) package that handles the standardization, pre-processing, and organization of these data.

**Expected Outcomes:**

The GSoC contributor will work with mentors to develop a new package **[echoshader](https://github.com/OSOceanAcoustics/echoshader)** that provides core ocean sonar data visualization functionalities based on the [HoloViz](https://github.com/holoviz/holoviz) suite of tools, test configuration for using echoshader widgets in [Panel](https://panel.holoviz.org/) dashboards, and create Jupyter notebooks to demo use of the combination of tools.

**Skills required:**
- Python
- Interest in working with oceanographic, acoustic and geospatial data

**Bonus skills:**
- Cloud computing
- Visualization

**Project Size:**
- 175 or 350 h

**Difficulty**
- Moderate

**Mentor(s):**
Wu-Jung Lee (@leewujung), Emilio Mayorga (@emiliom), Valentina Staneva (@valentina-s), Landung "Don" Setiawan (@lsetiawan), Brandon Reyes (@b-reyes)

**Comment by dwipddalal** [comment]
Hi.
I am Dwip Dalal sophomore at IIT Gandhinagar. I have been working with machine learning and data science for two years now. My passion for it has motivated me to take part in GSOC. After going through numerous organizations, I found IOOS very interesting; I am especially interested in using my data science and data visualization skills in geospatial analysis. Therefore, I would love to spend my summer working with and contributing to IOSS organization. I would love to work on the Interactive visualization of cloud-hosted ocean sonar data idea. 
Brief description about me:
In the last two years, I have interned in three companies, and currently, I am working with DRDO (Defence Research and Development Organisation of India), making Drone swarm AI. I am also working on analyzing fossils using data science with professor Pankaj Khaana IIT GN. I have done all this data science and data visualization work in python, so I am very familiar with the language. I have also done a couple of courses on cloud computing due to utter curiosity. 
To know more about me, please check out: https://www.linkedin.com/in/dwip-dalal-a7a440190
Respected Mentor,
I would be very grateful if you could please allocate me with some starter tasks. Looking forward to hearing from you soon.
Thank You

**Comment by leewujung** [comment]
Hey @dwipddalal, nice meeting you!  It's great to know that you're interested in this project. Do you want to do an introduction in the project repo [echoshader](https://github.com/OSOceanAcoustics/echoshader)?

You will see that we are in the process of populating resources and materials for the project, but we definitely welcome you to start asking questions and brainstorming ideas anytime!

**Comment by dwipddalal** [comment]
Yes I would love to introduce myself in the echoshader repo. Could you please suggest me in which specific section of the repo do I have to introduce myself?

**Comment by dwipddalal** [comment]
Should it be in issues tab with gsoc 2022 label?

**Comment by leewujung** [comment]
@dwipddalal: we think the best way is for you to ask a question and/or put in some ideas to brainstorm with us (the mentors). You can also make a profile on github that everyone can see, and in your application you will be able to introduce yourself more fully there! :)

**Comment by dwipddalal** [comment]
Sorry Sir for the late response. 
What I understood until now: We have to make functionalities for visualization of the  ocean sonar data using HoloViz toolkits.
Could you please let me know if my understanding of this project is correct or not?
I forgot to give my github profile: https://github.com/dwipddalal

**Comment by leewujung** [comment]
@dwipddalal : What I meant was that you should ask questions or post ideas for discussion in the echoshader repo linked above.

**Comment by dwipddalal** [comment]
Okay Sir.

**Comment by harshil15999** [comment]
Good Evening I have gone through all the issues and the current thread. Could you guide us to some good starter tasks and also perhaps some guidelines as to what has to be included in the proposal for GSOC.

**Comment by leewujung** [comment]
@harshil15999 : Welcome! 😃

Please go ahead to the echoshader repo: https://github.com/OSOceanAcoustics/echoshader and find relevant links in the README:
> For more information about joining the project as GSoC contributor, check out the IOOS GSoC Contributor Guidance and the Echoshader GSoC Contributor's Guide.

And start discussion with us!

**Comment by bitanb1999** [comment]
> **Project Description:**
> 
> Ocean sonar systems, such as echosounders, are the [workhorse to study life in the ocean](https://storymaps.arcgis.com/stories/e245977def474bdba60952f30576908f). They provide continuous observations of fish and zooplankton by transmitting sounds and analyzing the echoes bounced off these animals, just like how medical ultrasound images the interior of human body. In recent years these systems are widely deployed on ships, autonomous vehicles, or moorings, bringing in a lot of data that allow scientists to study the change of the marine ecosystem.
> 
> This project aims to create the capability to interactively visualize large, cloud-based ocean sonar data to accelerate data exploration and discovery. Developments in this project will go hand-in-hand with ongoing development of the [echopype](https://github.com/OSOceanAcoustics/echopype) package that handles the standardization, pre-processing, and organization of these data.
> 
> **Expected Outcomes:**
> 
> The GSoC contributor will work with mentors to develop a new package **[echoshader](https://github.com/OSOceanAcoustics/echoshader)** that provides core ocean sonar data visualization functionalities based on the [HoloViz](https://github.com/holoviz/holoviz) suite of tools, test configuration for using echoshader widgets in [Panel](https://panel.holoviz.org/) dashboards, and create Jupyter notebooks to demo use of the combination of tools.
> 
> **Skills required:**
> 
> * Python
> * Interest in working with oceanographic, acoustic and geospatial data
> 
> **Bonus skills:**
> 
> * Cloud computing
> * Visualization
> 
> **Project Size:**
> 
> * 175 or 350 h
> 
> **Difficulty**
> 
> * Moderate
> 
> **Mentor(s):** Wu-Jung Lee (@leewujung), Emilio Mayorga (@emiliom), Valentina Staneva (@valentina-s), Landung "Don" Setiawan (@lsetiawan), Brandon Reyes (@b-reyes)

Hello,
My name is Bitan Biswas and I am a Masters's student in Computer Science at the University of Calcutta and  a Research Assistant at Cardiff University. I have been working in the field of DataScience for three years  and my urge to learn more has got me to take part in Summer of Code. The work by IOOS seems extremely interesting and aligns with my interests in acoustic sound event detection and hyperspectral image visualization. I would be highly obliged if I am allowed to contribute to the echoshader repository and get involved in the project "Interactive visualization of cloud-hosted ocean sonar data" .

In the last two years, I have interned in six companies, and have been in working in the field of Data Analytics, Computer Vision, and NLP closely. I used the Bokeh package a couple of times, which seems to be relevant with the HoloViz tools. I have fluency in Python and other Object-Oriented Programming Languages and a certain preliminary understanding of cloud computing too. My LinkedIn is:https://www.linkedin.com/in/bitan-biswas-2544641b0/ and I would like to introduce myself in the echoshader repo and indulge in new ideas.

**Comment by ocefpaf** [comment]
Closing all past GSoC issues. Please open a new issue if you want to participate in GSoC23.
