### ISSUE TITLE
Add links to student project summaries after each GSOC year

### ISSUE THREAD

**Issue by mwengren** [ioos/gsoc#21]
We should at a minimum link to the summary report/page that each student submits at the end of their projects.

Ideally, make a GH pages site or some other way to present these in a compelling way.  If that's too complicated, we can just make a markdown page and list them out with links.

Hopefully, most of the places the students posted their reports are persistent (?)

**Comment by mwengren** [comment]
## 2021:

GSOC 2021 Portal IOOS org page: https://summerofcode.withgoogle.com/archive/2021/organizations/5159672092295168

- Qi Zeng: https://q1zeng.github.io/
- Callum Rollo: https://gist.github.com/callumrollo/ee28f7e1863d30162bdb041156314543
- Lohith Munakala: https://lohithmunakala.medium.com/seafloor-sampling-and-data-demo-center-jupyter-book-migration-gsoc21-ioos-a9930abc4c42

## 2022:

GSOC 2022 Portal IOOS org page: https://summerofcode.withgoogle.com/programs/2022/organizations/ioos

- Ayush Anand: https://ayushanand18.github.io/GSoC_design_documents/
- Dingrui Lei: https://github.com/OSOceanAcoustics/echoshader/wiki/Google-Summer-of-Code-2022
- Peter Marsh: https://github.com/fsspec/GSoC-kechunk-2022/blob/main/GSOC_monitor.md
- Vini Salazar: TBD

Easiest solution would be to link to each year's IOOS Org GSOC portal page since they present the projects in a clear way - we could just add that to the main README for this repo.

**Comment by MathewBiddle** [comment]
@ocefpaf has put together a nice write-up about this year's efforts. We should put that somewhere too.

**Comment by MathewBiddle** [comment]
we also have this page https://ioos.noaa.gov/news/summer-of-code-with-u-s-ioos/

**Comment by ocefpaf** [comment]
> @ocefpaf has put together a nice write-up about this year's efforts. We should put that somewhere too.

I shared the hackmd with out @mwengren. We can move that to this repo when we are done editing.

**Comment by mwengren** [comment]
I made a few small edits but it looks like a good writeup, let's post it.

How about if we turn the writeup into a results.md or project-results.md file or something like that and put it alongside the ideas list for 2022: https://github.com/ioos/gsoc/tree/main/2022?

Ideally, we should create something similar for 2021 and post it in the 2021 folder as well: https://github.com/ioos/gsoc/tree/main/2021.  Could you start that as well @ocefpaf ?

Then, we can make it easy to find each of those from the README somehow?

**Comment by ocefpaf** [comment]
> How about if we turn the writeup into a results.md or project-results.md file or something like that and put it alongside the ideas list for 2022: https://github.com/ioos/gsoc/tree/main/2022?

+1 (we should at least collect the links to where these are being published here to make it easier to find them for GSoC23.)

> Ideally, we should create something similar for 2021 and post it in the 2021 folder as well: https://github.com/ioos/gsoc/tree/main/2021. Could you start that as well @ocefpaf ?

Will do.

> Then, we can make it easy to find each of those from the README somehow?

We can link created an index in the README for those. I'll work on it.

**Comment by ocefpaf** [comment]
Done in #22
