### ISSUE TITLE
Plankton Imagery Processing

### ISSUE THREAD

**Issue by 7yl4r** [ioos/gsoc#31]
#### Project Description:

The SE Marine Biodiversity Observation Network program (SE MBON) is collecting 10’s of thousands of plankton images during oceanographic surveys across south Florida that must become publicly available  on several open-access repositories like [OBIS](https://obis.org/), [GBIF](https://www.gbif.org/), and [EcoTaxa](https://ecotaxa.obs-vlfr.fr/). In order to do this, an automated system for aligning taxonomic records extracted from imagery and associated metadata to the Darwin Core schema is needed. Plankton imagery is collected from > 80 stations during bi-monthly cruise in south Florida waters with a Continue Particle Imaging and Classification System (underwater microscope) mounted on a CTD-rosette.

#### Expected Outcomes:

The output from this project will be an R or Python package (or a combination of these programming languages) enabling users to align image-based taxonomic data and metadata to the Darwin Core standard and publish the data in the aforementioned data repositories. 

#### Skills required:
Python, R, experience with machine-learning-based image classification methods, knowledge of Darwin Core, image-upload API

#### Mentor(s):

Tylar Murray (@7yl4r), Enrique Montes (@eqmh), Mat Biddle (@MathewBiddle)

#### Expected Project Size (175 or 350 hours):

_175 hours_

#### Difficulty:

Medium

**Comment by mwengren** [comment]
Closing to clean up for GSoC 2024 application
