### ISSUE TITLE
Cloud-optimized package for interactive visualization of ocean sonar data

### ISSUE THREAD

**Issue by leewujung** [ioos/gsoc#35]
#### Project Description:

Ocean sonar systems, such as echosounders, are the [workhorse to study life in the ocean](https://storymaps.arcgis.com/stories/e245977def474bdba60952f30576908f). They provide continuous observations of fish and zooplankton by transmitting sounds and analyzing the echoes bounced off these animals, just like how medical ultrasound images the interior of human body. In recent years these systems are widely deployed on ships, autonomous vehicles, or moorings, bringing in a lot of data that allow scientists to study the change of the marine ecosystem. 

`echoshader` ([repo](https://github.com/OSOceanAcoustics/echoshader), [docs](https://echoshader.readthedocs.io/en/latest/intro.html)) is an open source Python package developed by GSoC’22 contributor Dingrei Lei ([@ldr426](https://github.com/ldr426)) to facilitate ocean sonar data visualization. It currently contains the basic building blocks for a variety of visualizations of ocean sonar data such as echogram plots, ship cruise maps, curtain 3D renderings. The goal of this GSoC project is to develop and test a robust cloud deployment of the package, and demonstrate the capabilities on several types of datasets.

The objectives are:
- test and optimize the toolbox for large datasets hosted on the cloud
- create a cloud-based demo of the functionalities
- improve code structure
- add functionality to annotate and visualize regions of interest

#### Expected Outcomes:

- A functional demo of the software on the cloud
- Software components easy to reuse by researchers

#### Skills required:

- Python, object oriented programming, cloud computing
- Interest in working with oceanographic, acoustic and geospatial data

**Bonus skills:**
- Visualization
- UX design
- Work with large datasets

#### Mentor(s):

Wu-Jung Lee ([@leewujung](https://github.com/leewujung)), Valentina Staneva ([@valentina-s](https://github.com/valentina-s))

#### Expected Project Size (175 or 350 hours):

175 or 350 h

#### Difficulty:

Medium

**Comment by 1e9abhi1e10** [comment]
@leewujung  Is IOOS selected for GSoC 2023, as I didn't the name?

**Comment by leewujung** [comment]
@1e9abhi1e10 : unfortunately it was not, but if you're interested in contributing let us know!

**Comment by praneethratna** [comment]
@leewujung Hey, I would like to contribute to this project, could you give a headstart on how do I start?

**Comment by leewujung** [comment]
@praneethratna: That's awesome! Just to make sure -- ioos was not selected as part of GSoC this year -- are you still interested in contributing in that case?

**Comment by praneethratna** [comment]
@leewujung Yeah, I'm aware of that and Interested in contributing.

**Comment by praneethratna** [comment]
Sure, will send you an email to contact as soon as i finish steps 1 and 2.

**Comment by praneethratna** [comment]
@leewujung One query, the step where data is being retrieved is taking quite a lot of time on my system and sometimes altogether crashing; I'm not sure of the exact reason, but is there any way to run the notebooks on colab or something?

**Comment by leewujung** [comment]
Hey @praneethratna : let's move these to the echoshader repo. Could you create an issue there and include info on which notebook(s) that you ran into problems, your computing environment, how you installed echopype, and the echopype version? Please reference this format: https://github.com/OSOceanAcoustics/echopype/issues/new?assignees=&labels=my_files_don%27t_convert&template=my-files-don-t-convert.md&title=%5BFile+conversion%5D+SUSPECT_CAUSE
I've received your email and will respond soon.

**Comment by praneethratna** [comment]
@leewujung You can find the issue that I have opened [here](https://github.com/OSOceanAcoustics/echoshader/issues/68) in echoshader repo.

**Comment by praneethratna** [comment]
@leewujung Hey, is this project still available for contribution?

**Comment by praneethratna** [comment]
@leewujung Hey, is this project still available for contribution? I would like to contribute to this project.

**Comment by praneethratna** [comment]
@leewujung Hey, I would like to contribute to this project
