### ISSUE TITLE
[GSoC Project Proposal]: IOOS_QC WebApp

### ISSUE THREAD

**Issue by ocefpaf** [ioos/gsoc#63]
### Project Description

Create a Web App using pyscript and/or pyodide

### Expected Outcomes

A user should be able to update a dataset and select the data checks they want to apply to it. Here is a prototype:

### Expected Project Size

None

### What is the difficulty of the project?

None

**Comment by MathewBiddle** [comment]
Looks like this is a duplicate of #64 Closing.

**Comment by ocefpaf** [comment]
I probably hit some key combination that opened this one before I finished typing. Sorry for the noise.
